/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.menu.view;

import java.io.FileInputStream;
import javazoom.jl.player.Player;

public class MenuView extends javax.swing.JFrame {

    static FileInputStream in;
    static Player p;
    static boolean isPlaying = true;
    

    public static void Music() {
        try {

            in = new FileInputStream("/Users/joao/Downloads/Menu/sons/zelda.mp3");
            p = new Player(in);
            p.play();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public static void stopMusic(){
        p.close();
    }
    

    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoNick = new javax.swing.JTextField();
        BotaoContinuar = new javax.swing.JButton();
        BotaoPararMusica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoNick.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNickActionPerformed(evt);
            }
        });
        getContentPane().add(TextoNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 280, 30));

        BotaoContinuar.setText("Continuar");
        BotaoContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 90, 30));

        BotaoPararMusica.setText("Parar Música");
        BotaoPararMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoPararMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPararMusicaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoPararMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/zelda.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 607));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoContinuarActionPerformed
        OptionsView telaOptions = new OptionsView();
        telaOptions.setVisible(true);
        this.setVisible(false);
        String nick = TextoNick.getText();
        System.out.println(nick);

    }//GEN-LAST:event_BotaoContinuarActionPerformed
    
    private void BotaoPararMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPararMusicaActionPerformed
        
        if(isPlaying == true){
            stopMusic();
            isPlaying = false;
        }
        else{
            Music();
            isPlaying = true;
        }
    }//GEN-LAST:event_BotaoPararMusicaActionPerformed

    private void TextoNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNickActionPerformed


    }//GEN-LAST:event_TextoNickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
        Music();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoContinuar;
    private javax.swing.JButton BotaoPararMusica;
    private javax.swing.JTextField TextoNick;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
